version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  tests:
    build: .
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test 